# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='客户端号')),
                ('Mark', models.CharField(max_length=50, verbose_name='分数')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2020, 4, 26, 15, 11, 8, 423537), verbose_name='更新时间')),
            ],
            options={
                'db_table': 'mark',
            },
        ),
    ]
