# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 03:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20200426_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(max_length=10000, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 11, 1, 59, 515352), verbose_name='更新时间'),
        ),
    ]
